Port: 5021,
EsHost: "http://192.168.10.33:9200",
ConsulAddress: "192.168.10.33:8500",
ConsulRegisterId: "logserver",
ConsulRegisterName: "logserver",
ConsulRegisterPort: 5022,
ConsulRegisterTags: "v0001",
ConsulRegisterAddress: "192.168.10.149",
ConsulCheckPort: 5022,
ConsulCheckTimeout: "3s",
ConsulCheckInterval: "5s",
DeregisterCriticalServiceAfter: "20s"